### ISSUE TITLE
Why doesn't the printer.newPage() function from cc:tweaked work? (Error: "unsupported operation")

### ISSUE THREAD

**Issue by Xkall2** [KosmosPrime/OpenComputers#10]
![2023-11-25_00 23 47](https://github.com/KosmosPrime/OpenComputers/assets/121384172/3b459e3f-5f36-4958-8b73-69f099893579)

**Comment by KosmosPrime** [comment]
The printer requires the actual printing to be done on the main thread (as it affects inventories) and to do so OC would have to schedule a CC-like Lua task execution. It's documented as

> Since we abstract away anything language specific, we cannot support the Lua context specific operations ComputerCraft provides.

In other words it's an upstream OC issue.
