### ISSUE TITLE
Shift+Insert clipboard paste doesn't work

### ISSUE THREAD

**Issue by astral17** [KosmosPrime/OpenComputers#13]
Shift+Insert key combination doesn't paste text from the clipboard. Paste from clipboard using the middle button works fine.
**dmesg demo 1.12.2 (OC 1.8.5):**
![image](https://github.com/KosmosPrime/OpenComputers/assets/20907711/f131fa99-c67f-49ec-8f1c-28a49182e3fa)
**dmesg demo 1.16.5 (OC 1.8.5.1):**
![image](https://github.com/KosmosPrime/OpenComputers/assets/20907711/78115274-273c-44a4-90bd-95b98dad7ffe)

**Comment by KosmosPrime** [comment]
This is probably working as intended. The port uses minecraft's keybinding system, and the default keybinding for clipboard paste is "insert" (not "shift + insert"). Forge makes it so that keybindings without modifier keys aren't activated if a modifier key (here: shift) is pressed.
