### ISSUE TITLE
Creative tablet computer.getDeviceInfo() error

### ISSUE THREAD

**Issue by astral17** [KosmosPrime/OpenComputers#15]
Creative tablet `computer.getDeviceInfo()` return nil with error message. No problem for tablets made inside assembler.

**How it looks 1.16.5 (OC 1.8.5.1):**
Creative tablet:
![image](https://github.com/KosmosPrime/OpenComputers/assets/20907711/ca0e69f4-25d5-4701-87a4-d5396d69bd65)
Handmade tablet:
![image](https://github.com/KosmosPrime/OpenComputers/assets/20907711/7403314a-8c36-4e68-bd25-7a51f3055e98)

**Comment by KosmosPrime** [comment]
Regression due to a change in how map data was handled. The fix replicates upstream OC behaviour, which means it'll create a new map for the creative (assembled) tablet which is centered around the world spawn (as opposed to the tablet's current location).
